### ISSUE TITLE
App not implemented on android

### ISSUE THREAD

**Issue by siddhant-dev** [aparajita/capacitor-biometric-auth#32]
Hi @aparajita 

I have implemented this plugin in capacitor 5 angular v17 and I'm using v7.1.1 of the plugin. 
For Some strange reason I'm getting the 

```ts
Error: "App" plugin is not implemented on android
    at createPluginMethod (index.js:188:23)
    at index.js:195:32
    at _ZoneDelegate.invoke (zone.js:368:26)
    at Zone.run (zone.js:130:43)
    at zone.js:1260:36
    at _ZoneDelegate.invokeTask (zone.js:403:31)
    at Zone.runTask (zone.js:174:47)
    at drainMicroTaskQueue (zone.js:582:35)
```

even though it does not break anything and the biometric run properly. I would like to understand why this is happening and will it impact in production. 

Below is the code for my implementation for reference

``` ts 
private async checkBiometry(): Promise<boolean> {
    try {
      const info: any = await BiometricAuth.checkBiometry();
      if (info.isAvailable) {
        return true;
      } else {
        this.Logger.warn(info);
        return false;
      }
    } catch (err) {
      this.Logger.error(err);
      return false;
    }
  }

  async savePassword(password: string, override = false) {
    try {
      const permission = this.PermissionService.checkPermission(
        'SOME_NAME'
      );
      const isPasswordSaved = this.checkPassword();
      const available: boolean = await this.checkBiometry();
      if (available && permission && !isPasswordSaved) {
        await BiometricAuth.authenticate({
          reason: this.TranslateService.instant(
            'CORE.BIOMETRIC.ASK_PERMISSION'
          ),
          cancelTitle: this.TranslateService.instant('CORE.BIOMETRIC.CANCEL'),
          allowDeviceCredential: true,
          iosFallbackTitle: this.TranslateService.instant(
            'CORE.BIOMETRIC.IOS_TITLE'
          ),
          androidTitle: this.TranslateService.instant(
            'CORE.BIOMETRIC.ANDROID_TITLE'
          ),
          androidConfirmationRequired: true,
          androidBiometryStrength: AndroidBiometryStrength.weak,
        });
        this.LocalStroageService.write(this.biometricKey, true);
        await this.SecureStorageService.secureData(this.key, password);
      }
    } catch (err) {
      this.Logger.error(err);
    }
  }

  async getPassword(): Promise<DataType | null> {
    try {
      const hasPassword = this.checkPassword();
      const available = await this.checkBiometry();

      if (hasPassword && available) {
        await BiometricAuth.authenticate({
          reason: this.TranslateService.instant('CORE.BIOMETRIC.TITLE'),
          cancelTitle: this.TranslateService.instant('CORE.BIOMETRIC.CANCEL'),
          allowDeviceCredential: true,
          iosFallbackTitle: this.TranslateService.instant(
            'CORE.BIOMETRIC.IOS_TITLE'
          ),
          androidTitle: this.TranslateService.instant(
            'CORE.BIOMETRIC.ANDROID_TITLE'
          ),
          androidConfirmationRequired: true,
          androidBiometryStrength: AndroidBiometryStrength.weak,
        });
        const password = this.SecureStorageService.getSecureData(this.key);
        return password;
      } else return null;
    } catch (err) {
      this.Logger.error(err);
      throw new Error('CORE.BIOMETRIC.RETERIVE_ERR');
    }
  }
```

**Comment by aparajita** [comment]
As stated in the first sentence of the README, this plugin is for Capacitor 6. I can only support Capacitor 6.

As stated in the docs, be sure to call BiometricAuth.checkBiometry before calling registerResumeCallback.

**Comment by siddhant-dev** [comment]
it is the registerResumeCallback that gives the error and I believe it is happening in capacitor 6 as well

**Comment by aparajita** [comment]
I don't see where you are calling registerResumeCallback.

**Comment by siddhant-dev** [comment]
Ahh! 
Apologies 

here is the modified code 

```ts 

private async checkBiometry(): Promise<void> {
    try {
      const info: any = await BiometricAuth.checkBiometry();
      this.isAvailable = info.isAvailable;
      this.appListener = await BiometricAuth.addResumeListener(info);
    } catch (err) {
      this.Logger.error(err);
      throw err;
    }
  }

  async savePassword(password: string, override = false): Promise<void> {
    try {
      const permission = this.PermissionService.checkPermission(
        'AUTH_ENABLED'
      );
      const isPasswordSaved = this.checkPassword();
      if (this.isAvailable && permission && !isPasswordSaved) {
        await BiometricAuth.authenticate({
          reason: this.TranslateService.instant(
            'CORE.BIOMETRIC.ASK_PERMISSION'
          ),
          cancelTitle: this.TranslateService.instant('CORE.BIOMETRIC.CANCEL'),
          allowDeviceCredential: true,
          iosFallbackTitle: this.TranslateService.instant(
            'CORE.BIOMETRIC.IOS_TITLE'
          ),
          androidTitle: this.TranslateService.instant(
            'CORE.BIOMETRIC.ANDROID_TITLE'
          ),
          androidConfirmationRequired: true,
          androidBiometryStrength: AndroidBiometryStrength.weak,
        });
        this.LocalStroageService.write(this.biometricKey, true);
        await this.SecureStorageService.secureData(this.key, password);
      }
    } catch (err) {
      this.Logger.error(err);
      throw err;
    }
  }

  async getPassword(): Promise<DataType | null> {
    try {
      const hasPassword = this.checkPassword();
      if (hasPassword && this.isAvailable) {
        await BiometricAuth.authenticate({
          reason: this.TranslateService.instant('CORE.BIOMETRIC.TITLE'),
          cancelTitle: this.TranslateService.instant('CORE.BIOMETRIC.CANCEL'),
          allowDeviceCredential: true,
          iosFallbackTitle: this.TranslateService.instant(
            'CORE.BIOMETRIC.IOS_TITLE'
          ),
          androidTitle: this.TranslateService.instant(
            'CORE.BIOMETRIC.ANDROID_TITLE'
          ),
          androidConfirmationRequired: true,
          androidBiometryStrength: AndroidBiometryStrength.weak,
        });
        const password = this.SecureStorageService.getSecureData(this.key);
        return password;
      } else return null;
    } catch (err) {
      this.Logger.error(err);
      throw new Error('CORE.BIOMETRIC.RETERIVE_ERR');
    }
  }

  private checkPassword() {
    return this.LocalStroageService.read(this.biometricKey);
  }

  onDestory() {
    this.appListener.remove();
  }
}
```

now I'm call the `checkBiometry()` in constructor so basically when the components gets mounted it gets called 
I also have `onDestory()`  function which is called when componented is destroyed

**Comment by aparajita** [comment]
Wait a minute, the error message is complaining about the App plugin, not this plugin.

**Comment by siddhant-dev** [comment]
yes I do http request that I await before this

**Comment by aparajita** [comment]
At the top level in main.ts? If you are using vite, there seems to be an issue with the code that esbuild generates when using top level await.

Try using then/catch instead.

**Comment by siddhant-dev** [comment]
ok thanks !
